// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCCIGZhVhJbkXMzxkXKzqqQd_JG2iYMoo',
    appId: '1:993013818553:web:5a712d677425bbee32a768',
    messagingSenderId: '993013818553',
    projectId: 'edtech-24298',
    authDomain: 'edtech-24298.firebaseapp.com',
    storageBucket: 'edtech-24298.appspot.com',
    measurementId: 'G-L4Y2R8QWNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ4XOm6LTQzO2a878xBsJl2X7-SMhISRc',
    appId: '1:993013818553:android:85508d1e5bfc0ec132a768',
    messagingSenderId: '993013818553',
    projectId: 'edtech-24298',
    storageBucket: 'edtech-24298.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9h54mEu6jrf44KDjIQsUE3eyNEyn5qA',
    appId: '1:993013818553:ios:57f2ace89c43b2b232a768',
    messagingSenderId: '993013818553',
    projectId: 'edtech-24298',
    storageBucket: 'edtech-24298.appspot.com',
    iosClientId: '993013818553-5dvtf0i8vct6pdm023bua344dkpm67uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.edtechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf9h54mEu6jrf44KDjIQsUE3eyNEyn5qA',
    appId: '1:993013818553:ios:57f2ace89c43b2b232a768',
    messagingSenderId: '993013818553',
    projectId: 'edtech-24298',
    storageBucket: 'edtech-24298.appspot.com',
    iosClientId: '993013818553-5dvtf0i8vct6pdm023bua344dkpm67uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.edtechApp',
  );
}
